### ISSUE TITLE
Projected eligibility for renewals

### ISSUE THREAD

**Issue by marthabmd** [dchealthlink/Haven#17]
This epic is the parent issue for all projected eligibility work for renewals for Plan Year 2019.

The basic plan for producing the projected eligibility is as follows:

- [x] Get initial case data pull from Stephen Haines (Tom to email asking for final format of last year's pull)
- [x] Take case file from Stephen and pull Curam pre-prod data into HAVEN pre-prod environment
- [ ] Updated expected contribution bands in HAVEN (need to get these from Sarah when they're available)
- [x] Produce projected eligibility and verify results (rinse and repeat as necessary)
- [x] Generate dump file for Enroll App
